// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YC4.Data;

#nullable disable

namespace YC4.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260129075149_UpdateUserIdToInt")]
    partial class UpdateUserIdToInt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YC4.Entity.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("YC4.Entity.Function", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FunctionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Functions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FunctionCode = "CONCERT_VIEW",
                            Name = "Xem Concert"
                        },
                        new
                        {
                            Id = 2,
                            FunctionCode = "CONCERT_CREATE",
                            Name = "Thêm Concert"
                        },
                        new
                        {
                            Id = 3,
                            FunctionCode = "Customer_MANAGEMENT",
                            Name = "Quản lý Khách hàng"
                        },
                        new
                        {
                            Id = 4,
                            FunctionCode = "CONCERT_UPDATE",
                            Name = "Cập nhật sự kiên"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Xem số ghế chưa được đặt của 1 sự kiên",
                            FunctionCode = "Available_Seat",
                            Name = "Xem số ghế"
                        },
                        new
                        {
                            Id = 6,
                            FunctionCode = "BOOK",
                            Name = "Đặt vé"
                        });
                });

            modelBuilder.Entity("YC4.Entity.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("YC4.Entity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Quản trị viên",
                            RoleCode = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Khách hàng",
                            RoleCode = "Customer"
                        });
                });

            modelBuilder.Entity("YC4.Entity.RoleFunction", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("FunctionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "FunctionId");

                    b.HasIndex("FunctionId");

                    b.ToTable("RoleFunctions");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            FunctionId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            FunctionId = 2
                        },
                        new
                        {
                            RoleId = 1,
                            FunctionId = 3
                        },
                        new
                        {
                            RoleId = 2,
                            FunctionId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            FunctionId = 4
                        },
                        new
                        {
                            RoleId = 1,
                            FunctionId = 5
                        },
                        new
                        {
                            RoleId = 2,
                            FunctionId = 5
                        },
                        new
                        {
                            RoleId = 1,
                            FunctionId = 6
                        },
                        new
                        {
                            RoleId = 2,
                            FunctionId = 6
                        });
                });

            modelBuilder.Entity("YC4.Entity.Seat", b =>
                {
                    b.Property<Guid>("SeatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("RowName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.HasKey("SeatId");

                    b.HasIndex("EventId");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("YC4.Entity.Ticket", b =>
                {
                    b.Property<Guid>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PriceAtBooking")
                        .HasColumnType("decimal(18,0)");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TicketId");

                    b.HasIndex("OrderId");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("YC4.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Sếp Tổng",
                            Password = "123",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Khách hàng",
                            Password = "123",
                            Username = "Customer"
                        });
                });

            modelBuilder.Entity("YC4.Entity.UserFunction", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("FunctionId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "FunctionId");

                    b.HasIndex("FunctionId");

                    b.ToTable("UserFunctions");
                });

            modelBuilder.Entity("YC4.Entity.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("YC4.Entity.RoleFunction", b =>
                {
                    b.HasOne("YC4.Entity.Function", "Function")
                        .WithMany("RoleFunctions")
                        .HasForeignKey("FunctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YC4.Entity.Role", "Role")
                        .WithMany("RoleFunctions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Function");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("YC4.Entity.Seat", b =>
                {
                    b.HasOne("YC4.Entity.Event", null)
                        .WithMany("Seats")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YC4.Entity.Ticket", b =>
                {
                    b.HasOne("YC4.Entity.Order", null)
                        .WithMany("Tickets")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YC4.Entity.UserFunction", b =>
                {
                    b.HasOne("YC4.Entity.Function", "Function")
                        .WithMany("UserFunctions")
                        .HasForeignKey("FunctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YC4.Entity.User", "User")
                        .WithMany("UserFunctions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Function");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YC4.Entity.UserRole", b =>
                {
                    b.HasOne("YC4.Entity.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YC4.Entity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YC4.Entity.Event", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("YC4.Entity.Function", b =>
                {
                    b.Navigation("RoleFunctions");

                    b.Navigation("UserFunctions");
                });

            modelBuilder.Entity("YC4.Entity.Order", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("YC4.Entity.Role", b =>
                {
                    b.Navigation("RoleFunctions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("YC4.Entity.User", b =>
                {
                    b.Navigation("UserFunctions");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
